services:
  - name: queer_conceptions
    plan: free
    type: web
    env: node
    repo: https://github.com/MBHunter88/queer_conceptions.git
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js or cd server && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []